version: '3.8'

services:
  langchain_api:
    build: .
    container_name: langchain_api
    restart: unless-stopped
    ports:
      - '9090:9090'

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - '11434:11434' # Default port for Ollama
    volumes:
      - ./ollama/ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    

volumes:
  ollama_data:
