version: '3.8'

services:
  langchain_api:
    build: .
    container_name: mindustry-gpt
    pull_policy: always
    restart: unless-stopped
    ports:
      - '9090:9090'
    networks:
      - my_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - '11434:11434' # Default port for Ollama
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ollama_data:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    networks:
      - my_network

volumes:
  ollama_data:

networks:
  my_network:
    driver: bridge
